name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: |
        echo Im inside a container
        repo init -u https://android.googlesource.com/platform/manifest -b android-8.1.0_r70
        container: kylemanna/aosp:latest
        name: Run in container
        
      
